v1.1.2 - error handling related to messages stream
airbytehq/pipelinewise-tap-twilio pull request #1
Opened 2021-03-12 14:59 UTC by yevhenii-ldv

## Problem

The stream of messages break when there was an attempt to receive messages more than 400 days ago.

2021-03-12 15:04 UTC, keu requested changes

2021-03-12 15:04 UTC, keu commented on tap_twilio/sync.py
> +                                    st_date = datetime.strptime('2020-01-01T00:00:00Z', "%Y-%m-%dT%H:%M:%SZ")
why we parse constant string here?

2021-03-12 15:07 UTC, yevhenii-ldv commented on tap_twilio/sync.py
> +                                    st_date = datetime.strptime('2020-01-01T00:00:00Z', "%Y-%m-%dT%H:%M:%SZ")
removed constant

2021-03-15 10:41 UTC, keu approved these changes

2021-03-15 11:06 UTC, merged

2021-03-15 18:28 UTC, sherifnada reviewed
LGTM